var cities = ["paris", "Dubai", "Florence", "intanbul", "hagar"];
console.log(cities);
var order_cities = cities.slice(0).sort();
console.log(order_cities);
console.log(cities);
revorder_cities = order_cities.reverse();
console.log(revorder_cities);
console.log(cities);
cities = cities.reverse();
console.log(cities);
cities = cities.reverse();
console.log(cities);
cities = cities.sort();
console.log(cities);
cities = cities.reverse();
console.log(cities);
